///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class FavoritesModelDataDataProduct {
/*
{
  "id": 60,
  "price": 487.5,
  "old_price": 554,
  "discount": 12,
  "image": "https://student.valuxapps.com/storage/uploads/products/1615451948lRQ93.item_XXL_122782705_d77430ea1a334.jpeg",
  "name": "Cressi DE203450 Skylight Silicone Wide-View Anti-UV Unisex Swimming Goggles - Black & Grey",
  "description": "Brand: Cressi\r\nThis mask uses mono-lens technology and the lenses are manufactured with an internal anti-fog treatment that are scratch-resistant and shatterproof.\r\nLenses: Slightly curved for excellent peripheral vision\r\nThe Silicone strap provides a secure and stable fit on the face for long periods in the water.\r\nEasy, adjustable buckle\r\nThe Skylight lenses in the mirrored and tinted version, block out the ultraviolet light, enabling the swimmer to see more clearly."
}
*/

  int? id;
  double? price;
  int? old_price;
  int? discount;
  String? image;
  String? name;
  String? description;

  FavoritesModelDataDataProduct({
    this.id,
    this.price,
    this.old_price,
    this.discount,
    this.image,
    this.name,
    this.description,
  });
  FavoritesModelDataDataProduct.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    price = json["price"]?.toDouble();
    old_price = json["old_price"]?.toInt();
    discount = json["discount"]?.toInt();
    image = json["image"]?.toString();
    name = json["name"]?.toString();
    description = json["description"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["price"] = price;
    data["old_price"] = old_price;
    data["discount"] = discount;
    data["image"] = image;
    data["name"] = name;
    data["description"] = description;
    return data;
  }
}

class FavoritesModelDataData {
/*
{
  "id": 10475,
  "product": {
    "id": 60,
    "price": 487.5,
    "old_price": 554,
    "discount": 12,
    "image": "https://student.valuxapps.com/storage/uploads/products/1615451948lRQ93.item_XXL_122782705_d77430ea1a334.jpeg",
    "name": "Cressi DE203450 Skylight Silicone Wide-View Anti-UV Unisex Swimming Goggles - Black & Grey",
    "description": "Brand: Cressi\r\nThis mask uses mono-lens technology and the lenses are manufactured with an internal anti-fog treatment that are scratch-resistant and shatterproof.\r\nLenses: Slightly curved for excellent peripheral vision\r\nThe Silicone strap provides a secure and stable fit on the face for long periods in the water.\r\nEasy, adjustable buckle\r\nThe Skylight lenses in the mirrored and tinted version, block out the ultraviolet light, enabling the swimmer to see more clearly."
  }
}
*/

  int? id;
  FavoritesModelDataDataProduct? product;

  FavoritesModelDataData({
    this.id,
    this.product,
  });
  FavoritesModelDataData.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    product = (json["product"] != null) ? FavoritesModelDataDataProduct.fromJson(json["product"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    if (product != null) {
      data["product"] = product!.toJson();
    }
    return data;
  }
}

class FavoritesModelData {
/*
{
  "current_page": 1,
  "data": [
    {
      "id": 10475,
      "product": {
        "id": 60,
        "price": 487.5,
        "old_price": 554,
        "discount": 12,
        "image": "https://student.valuxapps.com/storage/uploads/products/1615451948lRQ93.item_XXL_122782705_d77430ea1a334.jpeg",
        "name": "Cressi DE203450 Skylight Silicone Wide-View Anti-UV Unisex Swimming Goggles - Black & Grey",
        "description": "Brand: Cressi\r\nThis mask uses mono-lens technology and the lenses are manufactured with an internal anti-fog treatment that are scratch-resistant and shatterproof.\r\nLenses: Slightly curved for excellent peripheral vision\r\nThe Silicone strap provides a secure and stable fit on the face for long periods in the water.\r\nEasy, adjustable buckle\r\nThe Skylight lenses in the mirrored and tinted version, block out the ultraviolet light, enabling the swimmer to see more clearly."
      }
    }
  ],
  "first_page_url": "https://student.valuxapps.com/api/favorites?page=1",
  "from": 1,
  "last_page": 1,
  "last_page_url": "https://student.valuxapps.com/api/favorites?page=1",
  "next_page_url": null,
  "path": "https://student.valuxapps.com/api/favorites",
  "per_page": 35,
  "prev_page_url": null,
  "to": 10,
  "total": 10
}
*/

  int? current_page;
  List<FavoritesModelDataData?>? data;
  String? first_page_url;
  int? from;
  int? last_page;
  String? last_page_url;
  String? next_page_url;
  String? path;
  int? per_page;
  String? prev_page_url;
  int? to;
  int? total;

  FavoritesModelData({
    this.current_page,
    this.data,
    this.first_page_url,
    this.from,
    this.last_page,
    this.last_page_url,
    this.next_page_url,
    this.path,
    this.per_page,
    this.prev_page_url,
    this.to,
    this.total,
  });
  FavoritesModelData.fromJson(Map<String, dynamic> json) {
    current_page = json["current_page"]?.toInt();
    if (json["data"] != null) {
      final v = json["data"];
      final arr0 = <FavoritesModelDataData>[];
      v.forEach((v) {
        arr0.add(FavoritesModelDataData.fromJson(v));
      });
      this.data = arr0;
    }
    first_page_url = json["first_page_url"]?.toString();
    from = json["from"]?.toInt();
    last_page = json["last_page"]?.toInt();
    last_page_url = json["last_page_url"]?.toString();
    next_page_url = json["next_page_url"]?.toString();
    path = json["path"]?.toString();
    per_page = json["per_page"]?.toInt();
    prev_page_url = json["prev_page_url"]?.toString();
    to = json["to"]?.toInt();
    total = json["total"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["current_page"] = current_page;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["data"] = arr0;
    }
    data["first_page_url"] = first_page_url;
    data["from"] = from;
    data["last_page"] = last_page;
    data["last_page_url"] = last_page_url;
    data["next_page_url"] = next_page_url;
    data["path"] = path;
    data["per_page"] = per_page;
    data["prev_page_url"] = prev_page_url;
    data["to"] = to;
    data["total"] = total;
    return data;
  }
}

class FavoritesModel {
/*
{
  "status": true,
  "message": null,
  "data": {
    "current_page": 1,
    "data": [
      {
        "id": 10475,
        "product": {
          "id": 60,
          "price": 487.5,
          "old_price": 554,
          "discount": 12,
          "image": "https://student.valuxapps.com/storage/uploads/products/1615451948lRQ93.item_XXL_122782705_d77430ea1a334.jpeg",
          "name": "Cressi DE203450 Skylight Silicone Wide-View Anti-UV Unisex Swimming Goggles - Black & Grey",
          "description": "Brand: Cressi\r\nThis mask uses mono-lens technology and the lenses are manufactured with an internal anti-fog treatment that are scratch-resistant and shatterproof.\r\nLenses: Slightly curved for excellent peripheral vision\r\nThe Silicone strap provides a secure and stable fit on the face for long periods in the water.\r\nEasy, adjustable buckle\r\nThe Skylight lenses in the mirrored and tinted version, block out the ultraviolet light, enabling the swimmer to see more clearly."
        }
      }
    ],
    "first_page_url": "https://student.valuxapps.com/api/favorites?page=1",
    "from": 1,
    "last_page": 1,
    "last_page_url": "https://student.valuxapps.com/api/favorites?page=1",
    "next_page_url": null,
    "path": "https://student.valuxapps.com/api/favorites",
    "per_page": 35,
    "prev_page_url": null,
    "to": 10,
    "total": 10
  }
}
*/

  bool? status;
  String? message;
  FavoritesModelData? data;

  FavoritesModel({
    this.status,
    this.message,
    this.data,
  });
  FavoritesModel.fromJson(Map<String, dynamic> json) {
    status = json["status"];
    message = json["message"]?.toString();
    data = (json["data"] != null) ? FavoritesModelData.fromJson(json["data"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["status"] = status;
    data["message"] = message;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    return data;
  }
}
