///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class FavoritesModelDataDataProduct {

  int? id;
  double? price;
  int? old_price;
  int? discount;
  String? image;
  String? name;
  String? description;

  FavoritesModelDataDataProduct({
    this.id,
    this.price,
    this.old_price,
    this.discount,
    this.image,
    this.name,
    this.description,
  });
  FavoritesModelDataDataProduct.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    price = json["price"]?.toDouble();
    old_price = json["old_price"]?.toInt();
    discount = json["discount"]?.toInt();
    image = json["image"]?.toString();
    name = json["name"]?.toString();
    description = json["description"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["price"] = price;
    data["old_price"] = old_price;
    data["discount"] = discount;
    data["image"] = image;
    data["name"] = name;
    data["description"] = description;
    return data;
  }
}


class FavoritesModelData {


  int? current_page;
  List<FavoritesModelDataDataProduct?>? data;
  String? first_page_url;
  int? from;
  int? last_page;
  String? last_page_url;
  String? next_page_url;
  String? path;
  int? per_page;
  String? prev_page_url;
  int? to;
  int? total;

  FavoritesModelData({
    this.current_page,
    this.data,
    this.first_page_url,
    this.from,
    this.last_page,
    this.last_page_url,
    this.next_page_url,
    this.path,
    this.per_page,
    this.prev_page_url,
    this.to,
    this.total,
  });
  FavoritesModelData.fromJson(Map<String, dynamic> json) {
    current_page = json["current_page"]?.toInt();
    if (json["data"] != null) {
      final v = json["data"];
      final arr0 = <FavoritesModelDataDataProduct>[];
      v.forEach((v) {
        arr0.add(FavoritesModelDataDataProduct.fromJson(v));
      });
      this.data = arr0;
    }
    first_page_url = json["first_page_url"]?.toString();
    from = json["from"]?.toInt();
    last_page = json["last_page"]?.toInt();
    last_page_url = json["last_page_url"]?.toString();
    next_page_url = json["next_page_url"]?.toString();
    path = json["path"]?.toString();
    per_page = json["per_page"]?.toInt();
    prev_page_url = json["prev_page_url"]?.toString();
    to = json["to"]?.toInt();
    total = json["total"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["current_page"] = current_page;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["data"] = arr0;
    }
    data["first_page_url"] = first_page_url;
    data["from"] = from;
    data["last_page"] = last_page;
    data["last_page_url"] = last_page_url;
    data["next_page_url"] = next_page_url;
    data["path"] = path;
    data["per_page"] = per_page;
    data["prev_page_url"] = prev_page_url;
    data["to"] = to;
    data["total"] = total;
    return data;
  }
}

class SearchModel {

  bool? status;
  String? message;
  FavoritesModelData? data;

  SearchModel({
    this.status,
    this.message,
    this.data,
  });
  SearchModel.fromJson(Map<String, dynamic> json) {
    status = json["status"];
    message = json["message"]?.toString();
    data = (json["data"] != null) ? FavoritesModelData.fromJson(json["data"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["status"] = status;
    data["message"] = message;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    return data;
  }
}
